name: build-win-vcpkg

on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
  workflow_dispatch:
    inputs:
      ctestArgs:
        description: 'CTest arguments'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
      with:
          submodules: true

    - name: Install deps
      run: vcpkg install fontconfig freetype libxml2 openssl libjpeg-turbo libpng tiff

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -A x64 -DARCH=Win64 -DCMAKE_TOOLCHAIN_FILE=${{env.VCPKG_INSTALLATION_ROOT}}\scripts\buildsystems\vcpkg.cmake

      # NOTE: The cmake build is forced to be single
      # configuration (either Debug or Release) but it
      #  must be specified when running tests on Windows
      # because of MSVC solution oddities

    - name: Build
      run: cmake --build ${{github.workspace}}/build -config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest ${{ github.event.inputs.ctestArgs }}
